"use client";

// import type { Metadata } from "next"
import { Inter } from "next/font/google";
import React from "react";
import { ThemeProvider } from "@mui/material";
import theme from "@/lib/theme";
import Sidebar from "@/components/navigation/Sidebar";
import CssBaseline from "@mui/material/CssBaseline";
import { QueryClientProvider, QueryClient } from "@tanstack/react-query";

const inter = Inter({ subsets: ["latin"] });

const queryClient = new QueryClient();
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app"
// }

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <Sidebar>{children}</Sidebar>
          </ThemeProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
