"use client";

// import type { Metadata } from "next"
import { Inter } from "next/font/google";
import React from "react";
import { ThemeProvider } from "@mui/material";
import theme from "@/lib/theme";
import Sidebar from "@/components/navigation/Sidebar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app"
// }

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <Sidebar>{children}</Sidebar>
        </ThemeProvider>
      </body>
    </html>
  );
}
